name: Deploy to the Server

on:
  push:
    branches:
      - master # Change to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Install sshpass
      #   run: sudo apt-get install -y sshpass

      - name: Pull latest changes from GitHub
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@zizix6.com -p21098 << 'EOF'
          cd /home/zerothw/gloria
          git pull https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/GLOJEZ/glo.git master
          EOF
